{% set name = "opentelemetry-instrumentation-pyramid" %}
{% set version = "0.50b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_pyramid-{{ version }}.tar.gz
  sha256: f42e1b4158f157d0c1c3bccc2afe51e14b71a1f08c02746120d5a4248413aee6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-wsgi ==0.50b0
    - opentelemetry-instrumentation ==0.50b0
    - opentelemetry-semantic-conventions ==0.50b0
    - opentelemetry-util-http ==0.50b0
    - wrapt <2.0.0,>=1.0.0
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-pyramid 
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pyramid
  summary: OpenTelemetry Pyramid instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
