{% set name = "opentelemetry-instrumentation-pyramid" %}
{% set version = "0.52b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_pyramid-{{ version }}.tar.gz
  sha256: da5d36043507d2c4715851229c04f3e33fc21d8642df0b0387922ce1b4bdf2d5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation-wsgi ==0.52b1
    - opentelemetry-instrumentation ==0.52b1
    - opentelemetry-semantic-conventions ==0.52b1
    - opentelemetry-util-http ==0.52b1
    - wrapt <2.0.0,>=1.0.0
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-pyramid 
    # - werkzeug ==0.16.1
    # - pyramid >=1.7
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-pyramid 
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7
    # - pyramid >=1.7

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-pyramid
  summary: OpenTelemetry Pyramid instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
